### ISSUE TITLE
Création page SignIn/Signup

### ISSUE THREAD

**Issue by Omcci** [neolink78/Editoria#16]
- [ ] vérifier que le pseudo ne soit pas déjà pris en BDD
- [x] Mise en place d'une confirmation du mot de passe ?

**Comment by Omcci** [comment]
- [x] Réinitialisation mot de passe par mail
- [x] Sign-out
- [x] Protection des routes
- [x] Modification de la navbar

**Comment by Chl0l** [comment]
Revoir les loaders ! ! !
